[QDRANT]
url = "https://d9da8062-7ac5-46ca-9a98-cdb6561e520c.europe-west3-0.gcp.cloud.qdrant.io:6333"
api_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.1PSdadgsA0bI7aN_mBcD5AFk4zksd5ioaS-GeaTLfLA"

